### ISSUE TITLE
Encriptación de archivos

### ISSUE THREAD

**Issue by Edgar117** [Edgar117/LibroxProjectv2#1]
@davisaac19  por favor ya subí el cambio para registrar el libro, no se está guardando físicamente, solo la imagen verifícalo y me dices.
Puedes crear un usuario para hacer las pruebas correspondientes y cualquier error, por favor reportamelo o crea un Issues para verificarlo.
Cualquier duda o pregunta hazmelo saber por este medio o por mi correo.
Saludos

Edgar Daniel Vazquez Escobedo (CEO)

**Comment by davisaac19** [comment]
Ya verifiqué, ya pude ver que solo los PDF encripta y guarda, el original
no lo guarda, ahora probaré desencriptarlo. Saludos.

**Comment by davisaac19** [comment]
Este issue ya fue cerrado. La encriptación se realizó correctamente.
