### ISSUE TITLE
El DataList no hace bind al seleccionar un item para editar.

### ISSUE THREAD

**Issue by davisaac19** [Edgar117/LibroxProjectv2#2]
Un detalle es que en el datalist se tiene implementado un <edititemtemplate> que debe cargar cuando se hace clic en el botón editar mediante un command name, pero al hacerlo el datalist desaparece por completo, probablemente haga falta pasar algún argumento, dado que sí se dispara el evento 'onedititem'.

**Comment by davisaac19** [comment]
Asegúrate de crear un método independiente para hacer bind() al datalist; ya que, cuando la página hace postback el datalist pierde toda fuente de datos, y lo necesita de nuevo.

**Comment by Edgar117** [comment]
Claro lo tendré en cuenta. 
Gracias.
Saludos
